version: "2"

networks:
  kafka_net:

services:
  kafka:
    image: docker.io/bitnami/kafka:3.5
    ports:
      - "9092:9092"
    volumes:
      - "./kafka_data:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - kafka_net
    restart: always

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 16931:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - kafka_net
    volumes:
      - ./kui/config.yaml:/etc/kafkaui/dynamic_config.yaml
    restart: always
    depends_on:
      - kafka
volumes:
  kafka_data:
    driver: local
  kui:
    driver: local
